export const FRIEND_REQUEST_SENT = "FRIEND_REQUEST_SENT";
export const FRIEND_REQUEST_RECEIVED = "FRIEND_REQUEST_RECEIVED";
export const FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED";
export const FRIEND_REQUEST_REJECTED = "FRIEND_REQUEST_REJECTED";
export const FRIEND_REQUEST_CANCELED = "FRIEND_REQUEST_CANCELED";
